### ISSUE TITLE
Add embedded  video & logic of preferring video over image

### ISSUE THREAD

**Issue by vidhikesaria** [issoseva/issoseva.org#23]

**Comment by nojvek** [comment]
If fieldbook has video_url field, then we want to show a youtube embed for that url instead of the picture in projects section.

This will probably just require a change in the jade template.

**Comment by yogeshkhatri1989** [comment]
Done
embeds youtube video instead of image if present in `fieldbook/projects.json`
Sample embed youtube video url :- `https://www.youtube.com/embed/a3ICNMQW7Ok`
