### ISSUE TITLE
Fix sending message form 

### ISSUE THREAD

**Issue by nojvek** [issoseva/issoseva.org#3]

**Comment by vidhikesaria** [comment]
To be fixed by eod 09/16

When I hit send/submit, email with the message is sent to hello@issoseva.org. and we will show the below msg to customers - "Thank you for contacting us. We will get back to you shortly!"

**Comment by nojvek** [comment]
On the front end we would use jquery to make a ajax call to /api/email and send the message.

Api would send {success: true} or {error: "some message"}

On the front end we would show the thanks for contacting us message.

The api would use https://nodemailer.com/about/ with SMTP configuration.

**Comment by yogeshkhatri1989** [comment]
Done

**Comment by nojvek** [comment]
It seems this broke the main website http://issoseva.org

Could you revert your change please and send a PR with a sample smtp
config. I can add the config to the server.

The site is automatically deployed on every change to master, so we'll have
to be careful in merging directly to master.

**Comment by nojvek** [comment]
@yogeshkhatri1989 see http://status.issoseva.org 

I am reverting the change. Please send a PR with sample smtp

**Comment by yogeshkhatri1989** [comment]
oh it just skipped my mind to send you config.
i have sent you the PR for the same now, will carry on the same process onwards
