### ISSUE TITLE
when there are more than 3 events/testimonials (columns), the next row should be left aligned instead of right.

### ISSUE THREAD

**Issue by vidhikesaria** [issoseva/issoseva.org#31]
![image](https://user-images.githubusercontent.com/30166149/30944449-ac8630c2-a3ac-11e7-871e-3f498dcac0e5.png)

**Comment by yogeshkhatri1989** [comment]
i think you want it to be left aligned instead of right as in the screenshot/site its already right aligned.
So should i make it left aligned?

**Comment by nojvek** [comment]
Just fixed title. Left aligned should be the correct expected behaviour. Thanks @yogeshkhatri1989

**Comment by yogeshkhatri1989** [comment]
`main.scss` and `main.css` are not synced, are we doing changes directly in `main.css` file and should i also do changes in main.css?

**Comment by nojvek** [comment]
I would really love it if we operated everything off main.scss and added the transpilation to css as part of `fab deploy` which would run `yarn build` step when travis-ci runs.

Any chance you can investigate what differences there are and make main.scss the source of truth. We can remove the main.css completely from the repo.

Thanks for bringing this up @yogeshkhatri1989

**Comment by yogeshkhatri1989** [comment]
sure, will fix this.

**Comment by yogeshkhatri1989** [comment]
have changed `main.scss` to incorporate changes from `main.css`.
removed main.css and added compilation of css file on deploy in fabfile
please ensure sass is installed on server before merging/deploying

**Comment by nojvek** [comment]
Thanks. Will look at the PR

**Comment by nojvek** [comment]
Fixed by #32
