### ISSUE TITLE
Add testimonial section in homepage

### ISSUE THREAD

**Issue by vidhikesaria** [issoseva/issoseva.org#8]
Let's hook that up with fieldbook and have code ready - let's add validation that if there is no data the section doesn't show up (so code deployment is not tied to content availability once we have that hooked up I can add content)

**Comment by nojvek** [comment]
There is a testimonials table in fieldbook. Just need someone to fill it.

**Comment by vidhikesaria** [comment]
Assigning to Umeshbhai to add testimonial content

**Comment by vidhikesaria** [comment]
Can't find him yet - so will keep it to me
