### ISSUE TITLE
Update README.md to include info on how to get the site running locally and push new updates

### ISSUE THREAD

**Issue by vidhikesaria** [issoseva/issoseva.org#9]
@yogeshkhatri1989 now that you've pushed two updates. Any chance you can write a `Building locally` section in readme.md that includes the steps of what is required to get a locally running site. e.g installing node, npm, yarn, webpack, adding config, yarn sync_fieldbook and running the site.

Thanks.

**Comment by yogeshkhatri1989** [comment]
Done
